package com.bigoffs.rfid.database.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.bigoffs.rfid.mvp.bean.AllocationError;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ALLOCATION_ERROR".
*/
public class AllocationErrorDao extends AbstractDao<AllocationError, Long> {

    public static final String TABLENAME = "ALLOCATION_ERROR";

    /**
     * Properties of entity AllocationError.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property BoxCode = new Property(1, String.class, "boxCode", false, "BOX_CODE");
        public final static Property Rfid = new Property(2, String.class, "rfid", false, "RFID");
        public final static Property Incode = new Property(3, String.class, "incode", false, "INCODE");
    }


    public AllocationErrorDao(DaoConfig config) {
        super(config);
    }
    
    public AllocationErrorDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ALLOCATION_ERROR\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"BOX_CODE\" TEXT," + // 1: boxCode
                "\"RFID\" TEXT," + // 2: rfid
                "\"INCODE\" TEXT);"); // 3: incode
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ALLOCATION_ERROR\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, AllocationError entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String boxCode = entity.getBoxCode();
        if (boxCode != null) {
            stmt.bindString(2, boxCode);
        }
 
        String rfid = entity.getRfid();
        if (rfid != null) {
            stmt.bindString(3, rfid);
        }
 
        String incode = entity.getIncode();
        if (incode != null) {
            stmt.bindString(4, incode);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, AllocationError entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String boxCode = entity.getBoxCode();
        if (boxCode != null) {
            stmt.bindString(2, boxCode);
        }
 
        String rfid = entity.getRfid();
        if (rfid != null) {
            stmt.bindString(3, rfid);
        }
 
        String incode = entity.getIncode();
        if (incode != null) {
            stmt.bindString(4, incode);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public AllocationError readEntity(Cursor cursor, int offset) {
        AllocationError entity = new AllocationError( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // boxCode
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // rfid
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // incode
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, AllocationError entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setBoxCode(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setRfid(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setIncode(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(AllocationError entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(AllocationError entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(AllocationError entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
