package com.bigoffs.rfid.database.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.bigoffs.rfid.mvp.bean.GroundingDetailInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "GROUNDING_DETAIL_INFO".
*/
public class GroundingDetailInfoDao extends AbstractDao<GroundingDetailInfo, String> {

    public static final String TABLENAME = "GROUNDING_DETAIL_INFO";

    /**
     * Properties of entity GroundingDetailInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property InCode = new Property(0, String.class, "inCode", true, "IN_CODE");
        public final static Property BarCode = new Property(1, String.class, "barCode", false, "BAR_CODE");
        public final static Property ShelfCode = new Property(2, String.class, "shelfCode", false, "SHELF_CODE");
        public final static Property ICode = new Property(3, boolean.class, "iCode", false, "I_CODE");
        public final static Property BCode = new Property(4, boolean.class, "bCode", false, "B_CODE");
        public final static Property SCode = new Property(5, boolean.class, "sCode", false, "S_CODE");
        public final static Property Flag = new Property(6, long.class, "flag", false, "FLAG");
    }


    public GroundingDetailInfoDao(DaoConfig config) {
        super(config);
    }
    
    public GroundingDetailInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"GROUNDING_DETAIL_INFO\" (" + //
                "\"IN_CODE\" TEXT PRIMARY KEY NOT NULL ," + // 0: inCode
                "\"BAR_CODE\" TEXT," + // 1: barCode
                "\"SHELF_CODE\" TEXT," + // 2: shelfCode
                "\"I_CODE\" INTEGER NOT NULL ," + // 3: iCode
                "\"B_CODE\" INTEGER NOT NULL ," + // 4: bCode
                "\"S_CODE\" INTEGER NOT NULL ," + // 5: sCode
                "\"FLAG\" INTEGER NOT NULL );"); // 6: flag
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"GROUNDING_DETAIL_INFO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, GroundingDetailInfo entity) {
        stmt.clearBindings();
 
        String inCode = entity.getInCode();
        if (inCode != null) {
            stmt.bindString(1, inCode);
        }
 
        String barCode = entity.getBarCode();
        if (barCode != null) {
            stmt.bindString(2, barCode);
        }
 
        String shelfCode = entity.getShelfCode();
        if (shelfCode != null) {
            stmt.bindString(3, shelfCode);
        }
        stmt.bindLong(4, entity.getICode() ? 1L: 0L);
        stmt.bindLong(5, entity.getBCode() ? 1L: 0L);
        stmt.bindLong(6, entity.getSCode() ? 1L: 0L);
        stmt.bindLong(7, entity.getFlag());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, GroundingDetailInfo entity) {
        stmt.clearBindings();
 
        String inCode = entity.getInCode();
        if (inCode != null) {
            stmt.bindString(1, inCode);
        }
 
        String barCode = entity.getBarCode();
        if (barCode != null) {
            stmt.bindString(2, barCode);
        }
 
        String shelfCode = entity.getShelfCode();
        if (shelfCode != null) {
            stmt.bindString(3, shelfCode);
        }
        stmt.bindLong(4, entity.getICode() ? 1L: 0L);
        stmt.bindLong(5, entity.getBCode() ? 1L: 0L);
        stmt.bindLong(6, entity.getSCode() ? 1L: 0L);
        stmt.bindLong(7, entity.getFlag());
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public GroundingDetailInfo readEntity(Cursor cursor, int offset) {
        GroundingDetailInfo entity = new GroundingDetailInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // inCode
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // barCode
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // shelfCode
            cursor.getShort(offset + 3) != 0, // iCode
            cursor.getShort(offset + 4) != 0, // bCode
            cursor.getShort(offset + 5) != 0, // sCode
            cursor.getLong(offset + 6) // flag
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, GroundingDetailInfo entity, int offset) {
        entity.setInCode(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setBarCode(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setShelfCode(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setICode(cursor.getShort(offset + 3) != 0);
        entity.setBCode(cursor.getShort(offset + 4) != 0);
        entity.setSCode(cursor.getShort(offset + 5) != 0);
        entity.setFlag(cursor.getLong(offset + 6));
     }
    
    @Override
    protected final String updateKeyAfterInsert(GroundingDetailInfo entity, long rowId) {
        return entity.getInCode();
    }
    
    @Override
    public String getKey(GroundingDetailInfo entity) {
        if(entity != null) {
            return entity.getInCode();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(GroundingDetailInfo entity) {
        return entity.getInCode() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
