package com.bigoffs.rfid.database.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.bigoffs.rfid.mvp.bean.dao.InventoryCase;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "INVENTORY_CASE".
*/
public class InventoryCaseDao extends AbstractDao<InventoryCase, Long> {

    public static final String TABLENAME = "INVENTORY_CASE";

    /**
     * Properties of entity InventoryCase.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property ShelfCode = new Property(1, String.class, "shelfCode", false, "SHELF_CODE");
        public final static Property Incode = new Property(2, String.class, "incode", false, "INCODE");
        public final static Property RfidCode = new Property(3, String.class, "rfidCode", false, "RFID_CODE");
    }


    public InventoryCaseDao(DaoConfig config) {
        super(config);
    }
    
    public InventoryCaseDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"INVENTORY_CASE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"SHELF_CODE\" TEXT," + // 1: shelfCode
                "\"INCODE\" TEXT," + // 2: incode
                "\"RFID_CODE\" TEXT);"); // 3: rfidCode
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"INVENTORY_CASE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, InventoryCase entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String shelfCode = entity.getShelfCode();
        if (shelfCode != null) {
            stmt.bindString(2, shelfCode);
        }
 
        String incode = entity.getIncode();
        if (incode != null) {
            stmt.bindString(3, incode);
        }
 
        String rfidCode = entity.getRfidCode();
        if (rfidCode != null) {
            stmt.bindString(4, rfidCode);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, InventoryCase entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String shelfCode = entity.getShelfCode();
        if (shelfCode != null) {
            stmt.bindString(2, shelfCode);
        }
 
        String incode = entity.getIncode();
        if (incode != null) {
            stmt.bindString(3, incode);
        }
 
        String rfidCode = entity.getRfidCode();
        if (rfidCode != null) {
            stmt.bindString(4, rfidCode);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public InventoryCase readEntity(Cursor cursor, int offset) {
        InventoryCase entity = new InventoryCase( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // shelfCode
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // incode
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // rfidCode
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, InventoryCase entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setShelfCode(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setIncode(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setRfidCode(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(InventoryCase entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(InventoryCase entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(InventoryCase entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
