package com.bigoffs.rfid.database.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.bigoffs.rfid.mvp.bean.dao.PickCase;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PICK_CASE".
*/
public class PickCaseDao extends AbstractDao<PickCase, Long> {

    public static final String TABLENAME = "PICK_CASE";

    /**
     * Properties of entity PickCase.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Incode = new Property(1, String.class, "incode", false, "INCODE");
        public final static Property Shelf = new Property(2, String.class, "shelf", false, "SHELF");
        public final static Property Rfid = new Property(3, String.class, "rfid", false, "RFID");
        public final static Property IsReplace = new Property(4, boolean.class, "isReplace", false, "IS_REPLACE");
        public final static Property IsPick = new Property(5, boolean.class, "isPick", false, "IS_PICK");
    }


    public PickCaseDao(DaoConfig config) {
        super(config);
    }
    
    public PickCaseDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PICK_CASE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"INCODE\" TEXT," + // 1: incode
                "\"SHELF\" TEXT," + // 2: shelf
                "\"RFID\" TEXT," + // 3: rfid
                "\"IS_REPLACE\" INTEGER NOT NULL ," + // 4: isReplace
                "\"IS_PICK\" INTEGER NOT NULL );"); // 5: isPick
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PICK_CASE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, PickCase entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String incode = entity.getIncode();
        if (incode != null) {
            stmt.bindString(2, incode);
        }
 
        String shelf = entity.getShelf();
        if (shelf != null) {
            stmt.bindString(3, shelf);
        }
 
        String rfid = entity.getRfid();
        if (rfid != null) {
            stmt.bindString(4, rfid);
        }
        stmt.bindLong(5, entity.getIsReplace() ? 1L: 0L);
        stmt.bindLong(6, entity.getIsPick() ? 1L: 0L);
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, PickCase entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String incode = entity.getIncode();
        if (incode != null) {
            stmt.bindString(2, incode);
        }
 
        String shelf = entity.getShelf();
        if (shelf != null) {
            stmt.bindString(3, shelf);
        }
 
        String rfid = entity.getRfid();
        if (rfid != null) {
            stmt.bindString(4, rfid);
        }
        stmt.bindLong(5, entity.getIsReplace() ? 1L: 0L);
        stmt.bindLong(6, entity.getIsPick() ? 1L: 0L);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public PickCase readEntity(Cursor cursor, int offset) {
        PickCase entity = new PickCase( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // incode
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // shelf
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // rfid
            cursor.getShort(offset + 4) != 0, // isReplace
            cursor.getShort(offset + 5) != 0 // isPick
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, PickCase entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setIncode(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setShelf(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setRfid(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setIsReplace(cursor.getShort(offset + 4) != 0);
        entity.setIsPick(cursor.getShort(offset + 5) != 0);
     }
    
    @Override
    protected final Long updateKeyAfterInsert(PickCase entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(PickCase entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(PickCase entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
